// Code generated by entc, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// CharactersColumns holds the columns for the "characters" table.
	CharactersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID, Unique: true},
		{Name: "version", Type: field.TypeInt},
		{Name: "slot", Type: field.TypeInt, Default: 0},
		{Name: "size", Type: field.TypeInt, Default: 0},
		{Name: "data", Type: field.TypeString, SchemaType: map[string]string{"sqlite3": "text"}},
		{Name: "player_id", Type: field.TypeUUID},
	}
	// CharactersTable holds the schema information for the "characters" table.
	CharactersTable = &schema.Table{
		Name:       "characters",
		Columns:    CharactersColumns,
		PrimaryKey: []*schema.Column{CharactersColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "characters_players_characters",
				Columns:    []*schema.Column{CharactersColumns[5]},
				RefColumns: []*schema.Column{PlayersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "character_id",
				Unique:  false,
				Columns: []*schema.Column{CharactersColumns[0]},
			},
			{
				Name:    "character_player_id_slot_version",
				Unique:  false,
				Columns: []*schema.Column{CharactersColumns[5], CharactersColumns[2], CharactersColumns[1]},
			},
		},
	}
	// PlayersColumns holds the columns for the "players" table.
	PlayersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "steamid", Type: field.TypeString},
	}
	// PlayersTable holds the schema information for the "players" table.
	PlayersTable = &schema.Table{
		Name:       "players",
		Columns:    PlayersColumns,
		PrimaryKey: []*schema.Column{PlayersColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "player_id",
				Unique:  true,
				Columns: []*schema.Column{PlayersColumns[0]},
			},
			{
				Name:    "player_steamid",
				Unique:  true,
				Columns: []*schema.Column{PlayersColumns[1]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		CharactersTable,
		PlayersTable,
	}
)

func init() {
	CharactersTable.ForeignKeys[0].RefTable = PlayersTable
}
