// Code generated by entc, DO NOT EDIT.

package ent

import (
	"github.com/google/uuid"
	"github.com/msrevive/nexus2/internal/ent/character"
	"github.com/msrevive/nexus2/internal/ent/player"
	"github.com/msrevive/nexus2/internal/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	characterFields := schema.Character{}.Fields()
	_ = characterFields
	// characterDescVersion is the schema descriptor for version field.
	characterDescVersion := characterFields[2].Descriptor()
	// character.VersionValidator is a validator for the "version" field. It is called by the builders before save.
	character.VersionValidator = characterDescVersion.Validators[0].(func(int) error)
	// characterDescSlot is the schema descriptor for slot field.
	characterDescSlot := characterFields[3].Descriptor()
	// character.DefaultSlot holds the default value on creation for the slot field.
	character.DefaultSlot = characterDescSlot.Default.(int)
	// character.SlotValidator is a validator for the "slot" field. It is called by the builders before save.
	character.SlotValidator = characterDescSlot.Validators[0].(func(int) error)
	// characterDescSize is the schema descriptor for size field.
	characterDescSize := characterFields[4].Descriptor()
	// character.DefaultSize holds the default value on creation for the size field.
	character.DefaultSize = characterDescSize.Default.(int)
	// characterDescID is the schema descriptor for id field.
	characterDescID := characterFields[0].Descriptor()
	// character.DefaultID holds the default value on creation for the id field.
	character.DefaultID = characterDescID.Default.(func() uuid.UUID)
	playerFields := schema.Player{}.Fields()
	_ = playerFields
	// playerDescID is the schema descriptor for id field.
	playerDescID := playerFields[0].Descriptor()
	// player.DefaultID holds the default value on creation for the id field.
	player.DefaultID = playerDescID.Default.(func() uuid.UUID)
}
